### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by YoushaaMurhij** [chenyilun95/DSGN2#5]
Can you please provide more environment details?
I am facing a problem with pcdet build.
It would be great if you provide a conda env or a Dockerfile.

Thanks

**Comment by YoushaaMurhij** [comment]
Error Traceback:

```bash
Traceback (most recent call last):
  File "tools/train.py", line 13, in <module>
    from pcdet.datasets import build_dataloader
  File "/home/trainer/dsgn2/pcdet/datasets/__init__.py", line 5, in <module>
    from .kitti.lidar_kitti_dataset import LiDARKittiDataset
  File "/home/trainer/dsgn2/pcdet/datasets/kitti/lidar_kitti_dataset.py", line 10, in <module>
    from pcdet.utils import box_utils, calibration_kitti, common_utils, object3d_kitti
  File "/home/trainer/dsgn2/pcdet/utils/box_utils.py", line 7, in <module>
    from pcdet.ops.roiaware_pool3d import roiaware_pool3d_utils
  File "/home/trainer/dsgn2/pcdet/ops/roiaware_pool3d/roiaware_pool3d_utils.py", line 7, in <module>
    from . import roiaware_pool3d_cuda
ImportError: /home/trainer/dsgn2/pcdet/ops/roiaware_pool3d/roiaware_pool3d_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v
```

**Comment by chenyilun95** [comment]
Hi, could you check if the pytorch matches cuda verison? This error often occurs when they are not matched.

**Comment by SravanChittupalli** [comment]
@chenyilun95 Please provide a dockerfile. 

I am facing lots of issues with spconv and cumm intsallation.

Thanks

**Comment by azuryl** [comment]
> Hi, could you check if the pytorch matches cuda verison? This error often occurs when they are not matched.
can you tell us pytorch and  cuda version

I use cuda 10.2  conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch
have the issue too
 python -m pcdet.datasets.kitti.lidar_kitti_dataset create_kitti_infos
Traceback (most recent call last):
  File "/home/azuryl/anaconda3/envs/dsgn_j/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/azuryl/anaconda3/envs/dsgn_j/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/data/azuryl/DSGN2/pcdet/datasets/__init__.py", line 5, in <module>
    from .kitti.lidar_kitti_dataset import LiDARKittiDataset
  File "/data/azuryl/DSGN2/pcdet/datasets/kitti/lidar_kitti_dataset.py", line 10, in <module>
    from pcdet.utils import box_utils, calibration_kitti, common_utils, object3d_kitti
  File "/data/azuryl/DSGN2/pcdet/utils/box_utils.py", line 7, in <module>
    from pcdet.ops.roiaware_pool3d import roiaware_pool3d_utils
  File "/data/azuryl/DSGN2/pcdet/ops/roiaware_pool3d/roiaware_pool3d_utils.py", line 7, in <module>
    from . import roiaware_pool3d_cuda
ImportError: cannot import name 'roiaware_pool3d_cuda' from 'pcdet.ops.roiaware_pool3d' (unknown location)

**Comment by azuryl** [comment]
> @chenyilun95 Please provide a dockerfile.
> 
> I am facing lots of issues with spconv and cumm intsallation.
> 
> Thanks



> Hi, could you check if the pytorch matches cuda verison? This error often occurs when they are not matched.

please tell us which python version, which cuda version, which pytorch version you used

**Comment by Terry10086** [comment]
I use `python setup.py develop` to solve this problem. It seems that the environment needs to be installed before step 2

**Comment by chenyilun95** [comment]
I have ran the experiments with pytorch 1.7.1+cu101 and cu111.

> > @chenyilun95 Please provide a dockerfile.
> > I am facing lots of issues with spconv and cumm intsallation.
> > Thanks
> 
> > Hi, could you check if the pytorch matches cuda verison? This error often occurs when they are not matched.
> 
> please tell us which python version, which cuda version, which pytorch version you used

**Comment by zccz6** [comment]
> datasets

您好，我遇到了同样的问题，请问您问题解决了吗，谢谢
